version: '3.8'
services:
  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
  backend:
    build: ./backend
    ports: 
      - 4000:4000
    environment: 
      DB_URL: mongodb://db/mission-5

  db:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - mission-5:/data/db
volumes:
  mission-5:
    
